In [55]:
#import libraries
import numpy as nu
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sqlite3

In [47]:
#import database / data
conn=sqlite3.connect('customer_churn.db')

sql_query="""
SELECT name
FROM sqlite_master
WHERE type='table'
"""
tables=pd.read_sql(sql_query, conn)

#create dataframe for each table
for table_name in tables['name']:
    df=pd.read_sql(f"SELECT * FROM {table_name}", conn)
    globals()[f"df_{table_name}"]=df
    print(f"Created datarame: df_{table_name}")

conn.close()

Created datarame: df_db_customer
Created datarame: df_db_subscription
Created datarame: df_db_support

In [48]:
#data cleaning
df_db_customer.head()

,customerid,name,country,state,gender,dob,interests,pincode
0,0002-ORFBO,keshav,India,Maharashtra,Male,1982-04-12 00:00:00,travel,None
1,0003-MKNFE,raghav,India,Karnataka,Male,1995-11-23 00:00:00,NaN,None
2,0004-TLHLJ,lalita,India,Delhi,Female,1978-02-15 00:00:00,movie,None
3,0011-IGKFF,mohan,India,Nagaland,Male,2001-08-30 00:00:00,NaN,None
4,0013-EXCHZ,mira,India,Delhi,Female,1990-05-05 00:00:00,drama,None

In [49]:
df_db_customer.info

<bound method DataFrame.info of     customerid        name country          state  gender  \
0   0002-ORFBO      keshav   India    Maharashtra    Male
1   0003-MKNFE      raghav   India      Karnataka    Male
2   0004-TLHLJ      lalita   India          Delhi  Female
3   0011-IGKFF       mohan   India       Nagaland    Male
4   0013-EXCHZ        mira   India          Delhi  Female
5   0013-MHZWF       durga     NaN          Delhi   Women
6   0013-SMEOE        mina   India      Meghalaya  Female
7   0014-BMAQU       madan   India      Rajasthan    Male
8   0015-UOCOJ        maya     NaN      Kathmandu   Women
9   0016-QLJIS       arjun   Nepal      Kathmandu    Male
10  0017-DINOC       shiva   India    Maharashtra     Men
11  0017-IUDMW   rangadevi   India      Karnataka  Female
12  0018-NYROU      chitra     NaN      Telangana  Female
13  0019-EFAEP        raju   India      Meghalaya  Female
14  0019-GFNTW      Madhav   India  Uttar Pradesh     Men
15  0020-INWCK     parvati   India          Delhi  Female
16  0020-JDNXP       rikim   India      Meghalaya  Female
17  0021-IKXGC    vishakha   India      Rajasthan  Female
18  0022-TCJCI  raghvendra   India      Telangana    Male
19  0023-HGHWL     rishabh   India  Uttar Pradesh     Men
20  0023-UYUPN      sudevi   India    Maharashtra   Women

                    dob interests pincode
0   1982-04-12 00:00:00    travel    None
1   1995-11-23 00:00:00       NaN    None
2   1978-02-15 00:00:00     movie    None
3   2001-08-30 00:00:00       NaN    None
4   1990-05-05 00:00:00     drama    None
5   1988-12-10 00:00:00       NaN    None
6   1976-09-21 00:00:00       NaN    None
7   1999-03-14 00:00:00       NaN    None
8   1985-07-07 00:00:00       NaN    None
9   1993-10-29 00:00:00       NaN    None
10  1997-01-22 00:00:00       NaN    None
11  1981-06-18 00:00:00       NaN    None
12  2004-12-01 00:00:00       NaN    None
13  1992-04-25 00:00:00       NaN    None
14  1979-11-11 00:00:00       NaN    None
15  1986-02-28 00:00:00       job    None
16  1994-08-19 00:00:00       NaN    None
17  2000-09-02 00:00:00       NaN    None
18  1983-12-30 00:00:00       NaN    None
19  1991-05-14 00:00:00       NaN    None
20  1977-10-06 00:00:00       NaN    None  >

In [50]:
#a.rename columns-name
#b.drop columns-interest and pincode
#c.change data type-dob
#d.data standardization- gender
#e.fix missing values-country

In [51]:
#a. rename col-name
df_db_customer.rename(columns={'name': 'customer_name'},inplace=True)

In [52]:
#b.drop columns-interest and pincode
df_db_customer.drop(columns=['interests', 'pincode'])

,customerid,customer_name,country,state,gender,dob
0,0002-ORFBO,keshav,India,Maharashtra,Male,1982-04-12 00:00:00
1,0003-MKNFE,raghav,India,Karnataka,Male,1995-11-23 00:00:00
2,0004-TLHLJ,lalita,India,Delhi,Female,1978-02-15 00:00:00
3,0011-IGKFF,mohan,India,Nagaland,Male,2001-08-30 00:00:00
4,0013-EXCHZ,mira,India,Delhi,Female,1990-05-05 00:00:00
5,0013-MHZWF,durga,NaN,Delhi,Women,1988-12-10 00:00:00
6,0013-SMEOE,mina,India,Meghalaya,Female,1976-09-21 00:00:00
7,0014-BMAQU,madan,India,Rajasthan,Male,1999-03-14 00:00:00
8,0015-UOCOJ,maya,NaN,Kathmandu,Women,1985-07-07 00:00:00
9,0016-QLJIS,arjun,Nepal,Kathmandu,Male,1993-10-29 00:00:00
10,0017-DINOC,shiva,India,Maharashtra,Men,1997-01-22 00:00:00
11,0017-IUDMW,rangadevi,India,Karnataka,Female,1981-06-18 00:00:00
12,0018-NYROU,chitra,NaN,Telangana,Female,2004-12-01 00:00:00
13,0019-EFAEP,raju,India,Meghalaya,Female,1992-04-25 00:00:00
14,0019-GFNTW,Madhav,India,Uttar Pradesh,Men,1979-11-11 00:00:00
15,0020-INWCK,parvati,India,Delhi,Female,1986-02-28 00:00:00
16,0020-JDNXP,rikim,India,Meghalaya,Female,1994-08-19 00:00:00
17,0021-IKXGC,vishakha,India,Rajasthan,Female,2000-09-02 00:00:00
18,0022-TCJCI,raghvendra,India,Telangana,Male,1983-12-30 00:00:00
19,0023-HGHWL,rishabh,India,Uttar Pradesh,Men,1991-05-14 00:00:00
20,0023-UYUPN,sudevi,India,Maharashtra,Women,1977-10-06 00:00:00

In [53]:
#c.change data type-dob
df_db_customer['dob'] = pd.to_datetime(df_db_customer['dob'])

In [ ]:
#d.data standardization- gender
df_db_customer['gender'] = df_db_customer['gender'].replace({'Men': 'Male', 'Women': 'Female'})

,customerid,customer_name,country,state,gender,dob,interests,pincode
16,0020-JDNXP,rikim,India,Meghalaya,Female,1994-08-19,NaN,None
17,0021-IKXGC,vishakha,India,Rajasthan,Female,2000-09-02,NaN,None
18,0022-TCJCI,raghvendra,India,Telangana,Male,1983-12-30,NaN,None
19,0023-HGHWL,rishabh,India,Uttar Pradesh,Male,1991-05-14,NaN,None
20,0023-UYUPN,sudevi,India,Maharashtra,Female,1977-10-06,NaN,None

In [57]:
#e.fix missing values-country
df_db_customer[df_db_customer['country'].isna()]

,customerid,customer_name,country,state,gender,dob,interests,pincode
5,0013-MHZWF,durga,NaN,Delhi,Female,1988-12-10,NaN,None
8,0015-UOCOJ,maya,NaN,Kathmandu,Female,1985-07-07,NaN,None
12,0018-NYROU,chitra,NaN,Telangana,Female,2004-12-01,NaN,None

In [62]:
#country and state-unique value pair
state_country_mapping=df_db_customer.dropna(subset=['country']).set_index('state')['country'].to_dict()
df_db_customer['country'] = df_db_customer['country'].fillna(df_db_customer['state'].map(state_country_mapping))

In [65]:
df_db_customer[df_db_customer['country'].isna()]

Empty DataFrame
Columns: [customerid, customer_name, country, state, gender, dob, interests, pincode]
Index: []

In [66]:
df_db_subscription.head()

,customerid,subscription_start_date,subscription_type,renewal_date,plan_type,contract_type,cancellation_date,cancellation_reason,monthly_charges,cltv,churn_score
0,0002-ORFBO,2021-03-15,Refferal,2025-03-15,Standard,Annual,NaN,NaN,13.99,627,12
1,0003-MKNFE,2020-08-01,Paid,2024-08-01,Premium,Annual,2024-09-10,Switched to competitor,12.99,1150,91
2,0004-TLHLJ,2022-11-20,Organic,2025-11-20,Basic,Monthly,NaN,NaN,6.99,210,34
3,0011-IGKFF,2019-05-10,Paid,2025-05-10,Premium,Annual,NaN,NaN,22.99,1725,8
4,0013-EXCHZ,2023-01-05,Refferal,2024-01-05,Standard,Monthly,2024-02-28,Too expensive,13.99,195,88

In [67]:
df_db_subscription.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customerid               21 non-null     str
 1   subscription_start_date  21 non-null     str
 2   subscription_type        21 non-null     str
 3   renewal_date             21 non-null     str
 4   plan_type                21 non-null     str
 5   contract_type            21 non-null     str
 6   cancellation_date        6 non-null      str
 7   cancellation_reason      6 non-null      str
 8   monthly_charges          21 non-null     float64
 9   cltv                     21 non-null     int64
 10  churn_score              21 non-null     int64
dtypes: float64(1), int64(2), str(8)
memory usage: 1.9 KB

In [68]:
date_col=['subscription_start_date','renewal_date','cancellation_date']

df_db_subscription[date_col]=df_db_subscription[date_col].apply(pd.to_datetime)
df_db_subscription.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customerid               21 non-null     str
 1   subscription_start_date  21 non-null     datetime64[us]
 2   subscription_type        21 non-null     str
 3   renewal_date             21 non-null     datetime64[us]
 4   plan_type                21 non-null     str
 5   contract_type            21 non-null     str
 6   cancellation_date        6 non-null      datetime64[us]
 7   cancellation_reason      6 non-null      str
 8   monthly_charges          21 non-null     float64
 9   cltv                     21 non-null     int64
 10  churn_score              21 non-null     int64
dtypes: datetime64[us](3), float64(1), int64(2), str(5)
memory usage: 1.9 KB

In [69]:
df_db_support.head()

,customerid,complaint_date,escalations,csat_score,col_1,comment
0,0003-MKNFE,2024-08-28 00:00:00,N,60,None,service issue
1,0003-MKNFE,2024-08-28 00:00:00,Y,10,None,demaned refund
2,0013-EXCHZ,2024-01-20 00:00:00,Y,20,None,NaN
3,0013-MHZWF,2025-03-18 00:00:00,N,90,None,guidance to renew
4,0013-SMEOE,2024-11-01 00:00:00,N,30,None,NaN

In [70]:
df_db_support.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customerid      9 non-null      str
 1   complaint_date  9 non-null      str
 2   escalations     9 non-null      str
 3   csat_score      9 non-null      int64
 4   col_1           0 non-null      object
 5   comment         4 non-null      str
dtypes: int64(1), object(1), str(4)
memory usage: 564.0+ bytes

In [71]:
df_db_support.drop(columns=['col_1','comment'], inplace=True)

In [72]:
df_db_support['complaint_date'] = pd.to_datetime(df_db_support['complaint_date'])
df_db_support.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customerid      9 non-null      str
 1   complaint_date  9 non-null      datetime64[us]
 2   escalations     9 non-null      str
 3   csat_score      9 non-null      int64
dtypes: datetime64[us](1), int64(1), str(2)
memory usage: 420.0 bytes